### ISSUE TITLE
Reading follow stats missing

### ISSUE THREAD

**Issue by fr3fou** [GetStream/stream-go2#107]
The Reading Follow Stats API call is missing from the SDK as far as I can see.

![image](https://user-images.githubusercontent.com/1344906/120672285-d4da0e00-c49a-11eb-9d62-dd5843b96664.png)

It's crucial as some people might not want to fetch all of the data at once and only care about the count.

**Comment by ferhatelmas** [comment]
@fr3fou thanks for the notice. You're right. We were thinking to change server so postponed this implementation a bit.

However, server will be backward compatible, we can add. Will take care soon.
