### ISSUE TITLE
Random i/o timeouts and context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by fr3fou** [GetStream/stream-go2#110]
Using v5.7.0, some requests just randomly fail -
```
cannot perform request: Get "https://api.stream-io-api.com/api/v1.0/stats/follow/?api_key=<key>&followers=users<id>&following=<other-id>: dial tcp 18.206.166.98:443: i/o timeout
```
```
cannot perform request: Get "https://api.stream-io-api.com/api/v1.0/stats/follow/?api_key=<key>&followers=users<id>&following=<other-id>: dial tcp 18.206.166.98:443: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by ferhatelmas** [comment]
These are client timeouts, so network related.

1. be sure you're using the correct region (base url)
2. you can increase the timeout (default 3s)

**Comment by fr3fou** [comment]
> These are client timeouts, so network related.
> 
> 1. be sure you're using the correct region (base url)
> 2. you can increase the timeout (default 3s)

I'm using the closest region to me (Dublin) and the requests only sometime fail, once every few days

**Comment by ferhatelmas** [comment]
`stream.New(key, secret, stream.WithTimeout(6 * time.Second))`

adjust it according to your network quality. Nothing much we could do here.
You can observe your processing time in duration field in response. If it's high, let me know though. If you wish you can pass me your api key and I will see if really network is the problem.

> I'm using the closest region to me (Dublin)

Where are you connecting from? more or less?

**Comment by fr3fou** [comment]
> `stream.New(key, secret, stream.WithTimeout(6 * time.Second))`
> 
> adjust it according to your network quality. Nothing much we could do here.
> You can observe your processing time in duration field in response. If it's high, let me know though. If you wish you can pass me your api key and I will see if really network is the problem.
> 
> > I'm using the closest region to me (Dublin)
> 
> Where are you connecting from? more or less?

I'm connecting from Bulgaria, Dublin is indeed a bit far away from me so it can explain the latency. Are there any plans for servers in Germany?

**Comment by fr3fou** [comment]
Using a timeout of 10 seconds still causes issues.

**Comment by ferhatelmas** [comment]
> Are there any plans for servers in Germany / servers in EU East / EU Central?

Not sure, will check and let you know.

For the timeout, I suggest increasing further or retrying since it's a read, shouldn't a problem.

**Comment by ferhatelmas** [comment]
client has better keep alive settings and it should be resolved. If you still see, let us know please.
