### ISSUE TITLE
stream.WithCustomParam(..) not working?

### ISSUE THREAD

**Issue by nxcco** [GetStream/stream-go2#120]
As far as I understand, the method `WithCustomParam`, which returns `stream.GetActivitiesOption`, is for configuring the query in such a way, that the results contain this specified value for a given key. This matches also the request I saw, which gets constructed under the hood. However, all of queries I do ignore the custom param. 

### Example

`response, _ := timelineFlatFeed.GetActivities(stream.WithCustomParam("verb", "highlight"))`

The result contains activities with other values than "highlight".

Am I just confused and using it wrong, or is this an actual issue?

**Comment by ferhatelmas** [comment]
What is your goal ? filtering by verb ? If so, it's a supported feature in API. 

This option just enables to pass uncommon query parameters. There are many different parameters, instead of typing everything, this provides as shortcut or newer ones for old SDKs.

**Comment by ferhatelmas** [comment]
> Filtering it on the device/backend?

This is possible but it depends on how you setup your feeds.

Generally, you can create specific feeds for different verbs and let them follow each other such notes, videos, photos etc, then timeline follows all of them. Whenever you want a filtering, go to specific feed.

**Comment by nxcco** [comment]
Okay, thank you so much for clearifying that for me!
