### ISSUE TITLE
Unexpected time in new activity

### ISSUE THREAD

**Issue by InVincible2016** [GetStream/stream-go2#18]
We have timestamp = 1531760015 in unix time.

using this code to add a new activity to stream:
```
streamActivity := stream.Activity{
        Actor: actor,
        Verb: verb,
        Object: obj,
        Time: stream.Time{
					time.Unix(timestamp.ToInt64(), 0),
        },
        ForeignID: obj,
        To: feed_attributes.ConvertToStringArray(postActivity.To),
        Extra: map[string]interface{}{
          "rewards": postActivity.Rewards,
        },
      }
```
the result added activity have the time field as:
2018-07-16T12:53:35.000000

the expected result of the time field should be:
2018-07-16T16:53:35.000000

**Comment by tbarbugli** [comment]
Are you sure `timestamp` is localized as UTC before passing it to `time.Unix`?

**Comment by ruggi** [comment]
most likely this would solve your issue:
```go
...
Time: stream.Time{
	time.Unix(timestamp.ToInt64(), 0).UTC(),
},
...
```

**Comment by ruggi** [comment]
Closing this for now :)
