### ISSUE TITLE
Creating references should not require a stream client.

### ISSUE THREAD

**Issue by btipling** [GetStream/stream-go2#32]
Creating a reference to a type of collection just involves a string format, but because the SDK means by which to do it are attached to a type it requires creating a client to get the reference:

```go
// CreateReference returns a new reference string in the form SU:<id>.
func (c *UsersClient) CreateReference(id string) string {
	return fmt.Sprintf("SU:%s", id)
}
```

It seems unnecessary to need a `UsersClient` or a `Collection` to do this simple `fmt.Sprintf`. It may be the case someone might want to create a reference without having a client available, for example in tests, or because of how code was organized.

**Comment by ferhatelmas** [comment]
Makes sense and sorry for waiting. Added in https://github.com/GetStream/stream-go2/releases/tag/v4.3.0
