### ISSUE TITLE
Retrieving IDs on batch activity add

### ISSUE THREAD

**Issue by brunoluiz** [GetStream/stream-go2#51]
When using `AddToMany`, there seems to be no way to retrieve the published activities IDs. Is there a way to do this?

We've followed this: https://getstream.io/docs/add_many_activities/?language=go#batch_activity_add

**Comment by brunoluiz** [comment]
Dupe of https://github.com/GetStream/stream-go2/issues/52 -- Github was having issues while I was publishing the first one

**Comment by ferhatelmas** [comment]
@brunoluiz thanks for cleanup.
