### ISSUE TITLE
Retrieving activity IDs generated by AddToMany

### ISSUE THREAD

**Issue by brunoluiz** [GetStream/stream-go2#52]
When using `AddToMany`, there seems to be no way to retrieve the published activities IDs. Is there a way to do this?

We've followed this: https://getstream.io/docs/add_many_activities/?language=go#batch_activity_add

**Comment by ferhatelmas** [comment]
Your activity is added as a reference to all listed feeds so it will always have the same id irrespective of the feed it was being read.

To get the id, there are 2 ways:
* read any one of the feed
* specify `foreign id` and `time` on activity and retrieve activity by using [them](https://pkg.go.dev/github.com/GetStream/stream-go2/v4@v4.0.1?tab=doc#Client.GetActivitiesByForeignID)

**Comment by brunoluiz** [comment]
We ended up using the foreign id + time. Thanks 😉

**Comment by ferhatelmas** [comment]
Awesome, happy to hear that the problem is resolved.
