### ISSUE TITLE
[Proposal] Change of license to something more useable

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-go2#64]
It's blur if it's a problem while using but GPL might be pretty restrictive for many users. Having more liberal license and having a consistency between SDKs are good to haves.

**Comment by tbarbugli** [comment]
yes it was a mistake to license this with GPL, we should use a less restrictive one such as BSD

**Comment by ferhatelmas** [comment]
OK, I will update to BSD then with v5 (upcoming breaking changes due to rate limit headers in decoded responses)
