### ISSUE TITLE
How to check if an error is for rate limiting?

### ISSUE THREAD

**Issue by davidsbond** [GetStream/stream-go2#80]
Looking at the functionality of `NewRate`:

```go
func NewRate(headers http.Header) *Rate {
	var r Rate
	limit, err := strconv.Atoi(headers.Get(HeaderRateLimit))
	if err == nil {
		r.Limit = limit
	}
	remaining, err := strconv.Atoi(headers.Get(HeaderRateRemaining))
	if err == nil {
		r.Remaining = remaining
	}
	reset, err := strconv.ParseInt(headers.Get(HeaderRateReset), 10, 64)
	if err == nil && reset > 0 {
		r.Reset = Time{Time: time.Unix(reset, 0)}
	}
	return &r
}
```

It seems as though every response returned will have the rate information within it. From this, how do I deduce if an `APIError` is specifically for a rate limiting error? Is there a particular status code used? 

I think I can check if `r.Remaining` is zero, but is it possible for `r.Remaining` to be zero in responses that do not indicate hitting a rate limit?

**Comment by davidsbond** [comment]
Looking through the logs it seems that a `429` code is the one I want to check

**Comment by ferhatelmas** [comment]
@davidsbond Exactly and it's awesome, you're using go. Any suggestions to improve the library, please let me know.

Here, if it's an error, rate limiting is a part of the error. Otherwise, it's a part of the response. `http.StatusTooManyRequests` (429) is the error code.

**Comment by davidsbond** [comment]
Thanks @ferhatelmas. Only thing is the rate limit we hit was doing `unfollow_many`. I couldn't find what the actual limit is for that endpoint in your documentation.

https://getstream.io/docs/rate_limit_123 doesn't seem to have `Batch Unfollow`. It seems to have quite a low limit, as I think we only made ~20 requests

Otherwise your package is working great so far! Feels idiomatic and is doing a good job for us

**Comment by ferhatelmas** [comment]
@davidsbond Actually, we're reviewing docs this week to fix a couple of issues. Any suggestions/pointers are welcome. I will ensure it's added in that page.

Also, that endpoint is only available for enterprise customers unfortunately. For a possibility of increasing, please write to support.

**Comment by mo-hit** [comment]
@ferhatelmas as a suggestion could you maybe document that the unfollowMany method is enterprise only somewhere more visible? We were scratching our heads for a few days until we found this issue.

**Comment by ferhatelmas** [comment]
Definitely. Thank you for heads up. Added into docs. Also added the missing code snippets for this endpoint. 

You're very welcome to use question marks in docs to give feedback. Whenever you couldn't find something, hit the question mark and say what is missing then we will take care of adding a clarification or a pointer.

You can see the question mark at the top right:

![Screenshot from 2020-06-02 11-02-03](https://user-images.githubusercontent.com/648018/83501521-86c5af80-a4c0-11ea-9a34-87361c79e04b.png)
