### ISSUE TITLE
Policies/Permissions understanding

### ISSUE THREAD

**Issue by Emixam23** [GetStream/stream-go2#88]
Hey,

We finally have our feed system working but getting issues regarding the clients. In fact, when a client (let say user A) tries to get the feed of another user (user B), we get:

> You do not have permission to do this, you got this error because there are no policies allowing this request on this application

Now the issue is that we have some feed which are ("the_times", "_"), others that are ("users", "ID_HERE") and others that are ("timeline", "LOGGED_USER_ID")

In our conception, the "logged user" follows with his flat feed some ("users", "ID???") feed and post in his "users" feed.

As of now, we can post in our feed and see what we've published so far, but an user cannot access another user's flat feed ("users", "USER_ID") of a shared flat feed such as ("the_times", "_") 

I could see somewhere some stuff regarding permissions but I am really not sure to understand what's the issue here

Can you help me to better understand the issue i have please?

**Comment by ferhatelmas** [comment]
Anybody can follow anybody but reading is limited per documentation so we need to give some reading permissions to your feed groups.

However, this isn't related to SDK so closing, please explain required permission need in [support](https://getstream.io/support) with your app id and we will add them (if needed, private details of your app/code can be exchanged too)
