### ISSUE TITLE
 go get github.com/GetStream/stream-go2/v5 -- does this work?

### ISSUE THREAD

**Issue by ravieze** [GetStream/stream-go2#94]
hi,

as said in getting-started i executed the command

` go get github.com/GetStream/stream-go2/v5
`

and get the below error

`
C:\Users\ravie>go get github.com/GetStream/stream-go2/v5
package github.com/GetStream/stream-go2/v5: cannot find package "github.com/GetStream/stream-go2/v5" in any of:
        c:\go\src\github.com\GetStream\stream-go2\v5 (from $GOROOT)
        C:\Users\ravie\go\src\github.com\GetStream\stream-go2\v5 (from $GOPATH)
        D:\bfreecommons\src\github.com\GetStream\stream-go2\v5
`

but when i do 

`
 go get github.com/GetStream/stream-go2
`
the error goes off. but now i cannot create a client

`
stream "github.com/GetStream/stream-go2"
client, err := stream.NewClient(
		Stream_token,
		Stream_secret,
		stream.WithAPIRegion("us-east"),
		stream.WithAPIVersion("1.0"),
		stream.WithTimeout(10*time.Second),
	)
`

**Comment by ferhatelmas** [comment]
You need to ensure `GO111MODULE=on` because we require go modules.
