### ISSUE TITLE
The activity.foreign_id field is required on Update, not on Add

### ISSUE THREAD

**Issue by Emixam23** [GetStream/stream-go2#96]
Hey!

I have currently having a situation where I need to update some activities related to some feeds and, for some reason, it says that `activity.foreign_id field is required`, however, it's not required on insert.

The issue is that I get these activities using `GetActivitiesByID(activitiesIDs...)` and I just update the "Extra" properties of some activities. So they're the same activities objects, with no foreign_id set at all, from AddActivities, passing by GetActivitiesByID, to UpdateActivities, any idea?

```
// Inserting like this
func (getStream *GetStream) InsertContentsToFlatFeed(slug string, feedId string, contents []interface{}) (*[]*stream.Activity, error) {

	var res *stream.AddActivitiesResponse

	// Getting the flat feed
	flatFeed, err := getStream.client.FlatFeed(slug, feedId)
	if err != nil {
		return nil, err
	}

	var activities []stream.Activity
	for _, content := range contents {
		activities = append(activities, stream.Activity{
			Actor:  "timeline:_",
			Verb:   "some_verb",
			Object: "content:" + content.Id,
			Extra: map[string]interface{}{
				"user_id:": content.UserId,
				"content": []*models.ExtraActivityData{{
					ContentId: content.Id,
					Type:      content.Type,
				}},
			},
			Time: stream.Time{Time: getStream.helpers.FromTimestampToTime(socialInfoContent.GotAt)},
		})
	}

        res, err = flatFeed.AddActivities(activities...)
	if err != nil {
		return nil, err
	}

	var activitiesPtrs = make([]*stream.Activity, 0)
	for i, _ := range res.Activities {
		activitiesPtrs = append(activitiesPtrs, &res.Activities[i])
	}

	return &activitiesPtrs, nil

}

// .....

//  Getting like this:
func (getStream *GetStream) GetActivitiesByIDs(activitiesIDs []string) ([]*stream.Activity, error) {

	var activities = make([]*stream.Activity, 0)

	res, err := getStream.client.GetActivitiesByID(activitiesIDs...)
	if err != nil {
		return activities, errors.New(fmt.Sprintf("an error append while getting the activities: %v\n", err))
	}

	for _, elem := range res.Results {
		activities = append(activities, &elem)
	}

	return activities, nil
}

// .....

//  Updating like this:
func (getStream *GetStream) UpdateActivities(updatedActivities []stream.Activity) error {
	err := getStream.client.UpdateActivities(updatedActivities...)
	if err != nil {
		return errors.New(fmt.Sprintf("an error append while getting the activities: %v\n", err))
	}

	return nil
}
```

Thanks for helping me to understand if it's really an issue on my end

**Comment by ferhatelmas** [comment]
From [docs](https://getstream.io/docs/adding_activities/?language=go#updating-activities): 
> When you update an activity, you must include the following fields both when adding and updating the activity:time & foreign_id

Whenever you are missing these fields, you can use [partial activity update by id](https://getstream.io/docs/adding_activities/?language=go#activity-partial-update).

**Comment by Emixam23** [comment]
Hi, 

Thanks for the response. Can you just be a bit more specific on why is it acting like that? Why does `foreign_id` should be set on update, but not on add? What is its role?

Thanks

**Comment by ferhatelmas** [comment]
The pair (foreign_id, time) guarantees uniqueness. That's why upsert style update implementation can be done much more efficiently so update requires them. However, not all users need to update their activities so requiring them in add would be too limiting. In this case, partial update comes to rescue.

**Comment by Emixam23** [comment]
Okok, interesting :) Thanks for your answer :)
