### ISSUE TITLE
Could you create NewUnfollowRelationship() ?

### ISSUE THREAD

**Issue by Emixam23** [GetStream/stream-go2#99]
Hey,

While looking around I found (v5  stream package):

```
// NewFollowRelationship is a helper for creating a FollowRelationship from the
// source ("follower") and target ("following") feeds.
func NewFollowRelationship(source, target Feed, opts ...FollowRelationshipOption) FollowRelationship {
	r := FollowRelationship{
		Source: source.ID(),
		Target: target.ID(),
	}
	for _, opt := range opts {
		opt(&r)
	}
	return r
}
```

But you didn't create the **NewUnfollowRelationship** or something as, doesn't it?

I am using UnfollowMany and it takes similar parameters as FollowMany so I thought it could be good to point it out 👍

**Comment by ferhatelmas** [comment]
Not actually needed but for consistency, it might make sense. 

Do you want to send a PR ?

**Comment by Emixam23** [comment]
To be honest, I think I would prefer to let you do it :) The system is quite complex and I never made any PR on public git so... do you mind doing it yourself? So I ain't breaking nothing ^^
